### ISSUE TITLE
Operator '\otimes' won't display

### ISSUE THREAD

**Issue by baillyga** [stefano-meschiari/latex2exp#57] opened 2022-12-14 14:46 UTC
Hello,

Some operators such as \times and \otimes wil only display a white square. I am using version 4.2.1 of R.

```r
library(latex2exp)
plot(TeX(r"($Z \otimes D_{jk}$)")) # displays white square instead of \otimes, see picture
```

![image](https://user-images.githubusercontent.com/73058356/207626497-6597f451-d2a6-45f4-83aa-c65237107f71.png)

**Comment by stefano-meschiari** [comment] 2022-12-14 17:20
Hello,

Could you paste the output of `sessionInfo()`? Do you know what device is being used for plotting?

**Comment by stefano-meschiari** [comment] 2022-12-29 03:44
Closing since I was not able to reproduce. Feel free to reopen this issue if you can provide steps to reproduce the bug.

**Closed as completed by stefano-meschiari** 2022-12-29 03:44 UTC
